### ISSUE TITLE
Hermetyzacja

### ISSUE THREAD

**Issue by Dobiks** [Dobiks/ChessRobot#2]
Dlaczego pomimo hermetyzacji można zmieniac pola klasy cFigura w scena.cpp 
np. figury[1].x_->0;

**Comment by piokac** [comment]
w klasie cFigura jest: friend class cScena;
Jeśli chodzi o prawidłowy wzorzec, to zaprzyjaśnianie elementu z klasą kontenera jest niepoprawne

**Comment by Dobiks** [comment]
Dziękuję za odpowiedź. Usunąłem zaprzyjaźnienie na rzecz setterów i getterów.
